import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import {aggregatePizzaMandatoryV1,quantidadeEfetivaItemObrigatorio} from '../supabase/functions/raffinato-relay/pizza-mandatory-v1.mjs';

const relay=fs.readFileSync('supabase/functions/raffinato-relay/index.ts','utf8');
const frontend=fs.readFileSync('assets/js/96-raffinato-item-obrigatorio-pizza.js','utf8');
const connector=fs.readFileSync('tools/raffinato-bridge/raffinato_bridge.py','utf8');
const base={id_venda:1,id_pai:10,id_item:11,produto_pai:'CAFÉ NESTLE',agrupamento_pai:'CAFÉS',id_grupo_obrigatorio:7,grupo_obrigatorio:'CAFE NESCAFE',componente:'CAPPUCCINO',quantidade_produto_principal:2,quantidade_componente:1,valor_unitario_componente:9.99,valor_componente:19.98,modulo_venda:'DELIVERY',canal_venda:'iFood',situacao_venda:'EM_ABERTO',cancelado:false};

test('nome funcional é genérico e rota interna é preservada',()=>{assert.match(frontend,/Raffinato – Venda de Item Obrigatório/);assert.match(frontend,/relatorio_item_obrigatorio_pizza/);assert.doesNotMatch(frontend,/Pizzas \/ pais|Sabores por composição/)});
test('frontend não escolhe filial e mantém módulo, canal e situação separados',()=>{assert.doesNotMatch(frontend,/localhost|127\.0\.0\.1/);assert.match(frontend,/hasOwnProperty\.call\(payload,'id_filial'\)/);assert.match(frontend,/iopModule/);assert.match(frontend,/iopChannel/);assert.match(frontend,/iopSituation/)});
test('SQL parte de Venda gravada e da relação estrutural pai-filho',()=>{assert.match(connector,/FROM dbo\.Venda V/);assert.match(connector,/VI\.IdItemPai IS NOT NULL/);assert.match(connector,/PAI\.Id=VI\.IdItemPai/);assert.match(connector,/VI\.IdAgrupamentoItemObrigatorio IS NOT NULL/);assert.match(connector,/CASE WHEN VI\.IdStatusItem=2 OR PAI\.IdStatusItem=2/);assert.doesNotMatch(connector,/INNER JOIN dbo\.PagamentoVenda/)});
test('metadados incluem agrupamentos usados mesmo bloqueados para venda avulsa',()=>{const sql=connector.slice(connector.indexOf('SQL_PIZZA_MANDATORY_METADATA_V1'),connector.indexOf('SQL_PIZZA_STOCK_RETURN'));assert.match(sql,/AgrupamentoItemObrigatorio/);assert.doesNotMatch(sql,/BloqueiaVenda/)});
test('valor histórico vem da linha filha e preço atual não é consultado',()=>{assert.match(connector,/VI\.ValorUnitario/);assert.match(connector,/VI\.ValorTotal/);assert.doesNotMatch(connector,/\*\s*1\.35|1\.35\s*\*/)});
test('quantidade efetiva reconhece caso 1 x 9,99 com total 19,98 e pai 2',()=>{assert.deepEqual(quantidadeEfetivaItemObrigatorio(base),{quantidade:2,criterio:'valor_total_confirma_quantidade_pai'})});
test('pai com dois filhos é contado uma vez e valores dos filhos são somados',()=>{const d=aggregatePizzaMandatoryV1([base,{...base,id_item:12,componente:'EXPRESSO',quantidade_componente:2,valor_unitario_componente:7,valor_componente:14}]);assert.equal(d.resumo.pais_vendidos,2);assert.equal(Math.round(d.resumo.valor_itens*100),3398);assert.equal(d.records.length,2)});
test('venda aberta aparece e após finalizar não duplica',()=>{const aberta=aggregatePizzaMandatoryV1([base]);const final=aggregatePizzaMandatoryV1([{...base,situacao_venda:'FINALIZADA'}]);assert.equal(aberta.resumo.vendas_gravadas,1);assert.equal(aberta.resumo.vendas_abertas,1);assert.equal(final.resumo.vendas_gravadas,1);assert.equal(final.resumo.vendas_finalizadas,1)});
test('cancelado não compõe venda líquida',()=>{const d=aggregatePizzaMandatoryV1([{...base,cancelado:true}]);assert.equal(d.resumo.valor_itens,0);assert.equal(d.resumo.vendas_gravadas,0);assert.equal(d.resumo.cancelados,1)});
test('preços Loja e iFood permanecem históricos e separados',()=>{const d=aggregatePizzaMandatoryV1([{...base,id_venda:1,id_pai:10,id_item:11,modulo_venda:'VENDA_RAPIDA',canal_venda:'LOJA_MANUAL',valor_unitario_componente:9.99,valor_componente:9.99,quantidade_produto_principal:1},{...base,id_venda:2,id_pai:20,id_item:21,valor_unitario_componente:13.49,valor_componente:13.49,quantidade_produto_principal:1}]);assert.deepEqual(d.records.map(x=>x.valor_unitario),[9.99,13.49]);assert.equal(d.resumo.valor_itens,23.48)});
test('módulos usam vínculos prioritários e preservam origem desconhecida',()=>{assert.match(connector,/ORIGEM_INCONSISTENTE/);assert.match(connector,/VendaTeleEntrega/);assert.match(connector,/VendaCartaoConsumo/);assert.match(connector,/VendaMesa/);assert.match(connector,/VendaMobilidade/);assert.match(connector,/SEM_ORIGEM/);assert.match(connector,/OUTRO_MODULO/)});
test('relay mantém isolamento por empresa loja filial e versão',()=>{assert.match(relay,/eq\("empresa_id",body\.empresa_id\).*eq\("loja_id",body\.loja_id\).*eq\("id_filial",filial\)/);assert.match(relay,/id_grupo_obrigatorio/)});
